apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: bookinfo-reviews-build-deploy-
spec:
  pipelineRef:
    name: build-deploy-bookinfo-reviews
  serviceAccountName: pipeline
  params:
  - name: buildRevision
    value: '586d7fd1a8a33060828874bc4d2df78f0e913399'
  - name: appGitUrl
    value: 'git@github.com:ajoyacharyya/bookinfo-reviews.git'
  - name: configGitUrl
    value: 'git@github.com:ajoyacharyya/bookinfo-config.git'
  - name: appImage
    value: 'ajoyacharyya/bookinfo-reviews'
  - name: github-app-name
    value: bookinfo-reviews
  workspaces:
  - name: app-source
    emptyDir: {}
  - name: config-source
    emptyDir: {}
---
