apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: bookinfo-details-build-deploy-
spec:
  pipelineRef:
    name: build-deploy-bookinfo-details
  serviceAccountName: pipeline
  params:
  - name: buildRevision
    value: 'beb3666e183d8898bc101dcdf2063ee2a4c22f39'
  - name: appGitUrl
    value: 'git@github.com:ajoyacharyya/bookinfo-details.git'
  - name: configGitUrl
    value: 'git@github.com:ajoyacharyya/bookinfo-config.git'
  - name: appImage
    value: 'ajoyacharyya/bookinfo-details'
  - name: github-app-name
    value: bookinfo-details
  workspaces:
  - name: app-source
    emptyDir: {}
  - name: config-source
    emptyDir: {}
---
