apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-systemtest
spec:
  params:
  - name: gateway
  - name: buildRevision
  - name: appGitUrl
  workspaces:
  - name: app-source
  steps:
  - name: running-systemtest
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.app-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e

      eval $(ssh-agent)
      ssh-add ~/.ssh/id_*
      git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=accept-new'

      echo "Running System Test"

  - name: systemtest-final
    image: ajoyacharyya/maven-jdk14:quarkus-deps-1.5.1-b1
    workingDir: "$(workspaces.app-source.path)"
    command:
    - [echo, "Running System Test"]

---