apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker
spec:
  params:
  - name: buildRevision
  - name: appGitUrl
  - name: appImage
  - name: github-app-name
  workspaces:
  - name: app-source

  steps:
  - name: git-checkout
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.app-source.path)/$(params.github-app-name)"
    script: |
      #!/usr/bin/env sh
      set -e

      eval $(ssh-agent)
      ssh-add ~/.ssh/id_*
      git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=accept-new'

      git init
      git remote add origin $(params.appGitUrl)
      git fetch --depth 1 origin $(params.buildRevision)
      git checkout FETCH_HEAD

  - name: build-image
    image: quay.io/buildah/stable
    workingDir: "$(workspaces.app-source.path)/$(params.github-app-name)"
    command: ['buildah', 'bud', '--tls-verify=false', '--layers', '-f', 'Dockerfile', '-t', '$(params.appImage):$(params.buildRevision)', '.']
    volumeMounts:
    - name: varlibc
      mountPath: /var/lib/containers
    securityContext:
      allowPrivilegeEscalation: true
      runAsUser: 0
      privileged: true

  - name: build-push
    image: quay.io/buildah/stable
    command: ["buildah", "push", "--tls-verify=false", "$(params.appImage):$(params.buildRevision)", "docker://$(params.appImage):$(params.buildRevision)"]
    volumeMounts:
    - name: varlibc
      mountPath: /var/lib/containers
    securityContext:
      allowPrivilegeEscalation: true
      runAsUser: 0
      privileged: true

  volumes:
  - name: varlibc
    emptyDir: {}
---
