apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-systemtest
spec:
  params:
  - name: gateway
  - name: buildRevision
  - name: appGitUrl
  workspaces:
  - name: app-source
  steps:
  - name: running-systemtest
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.app-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e

      echo "Running System Test"
---