apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-pipeline
  namespace: argocd
spec:
  destination:
    namespace: tekton-pipelines
    server: https://kubernetes.default.svc
  project: default
  source:
    path: pipelines
    repoURL: https://github.com/ajoyacharyya/bookinfo-config.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
---
