apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-prod
  namespace: argocd
spec:
  destination:
    namespace: production-bookinfo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-config-production
    repoURL: https://github.com/ajoyacharyya/bookinfo-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
