apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy-template-bookinfo-ratings
  namespace: tekton-pipelines
spec:
  params:
  - name: buildRevision
    description: The Git commit revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-deploy-bookinfo-ratings-
    spec:
      pipelineRef:
        name: build-deploy-bookinfo-ratings
      serviceAccountName: pipeline
      params:
      - name: buildRevision
        value: $(tt.params.buildRevision)
      - name: appGitUrl
        value: 'git@github.com:ajoyacharyya/bookinfo-ratings.git'
      - name: configGitUrl
        value: 'git@github.com:ajoyacharyya/bookinfo-config.git'
      - name: appImage
        value: 'ajoyacharyya/bookinfo-ratings'
      - name: github-app-name
        value: bookinfo-ratings
      workspaces:
      - name: app-source
        emptyDir: {}
      - name: config-source
        emptyDir: {}
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-deploy-binding-bookinfo-ratings
  namespace: tekton-pipelines
spec:
  params:
  - name: buildRevision
    value: $(body.head_commit.id)
---
