apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy-template-bookinfo-productpage
  namespace: tekton-pipelines
spec:
  params:
  - name: buildRevision
    description: The Git commit revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-deploy-bookinfo-productpage-
    spec:
      pipelineRef:
        name: build-deploy-bookinfo-productpage
      serviceAccountName: pipeline
      params:
      - name: buildRevision
        value: '586d7fd1a8a33060828874bc4d2df78f0e913399'
      - name: appGitUrl
        value: 'git@github.com:ajoyacharyya/bookinfo-productpage.git'
      - name: configGitUrl
        value: 'git@github.com:ajoyacharyya/bookinfo-config.git'
      - name: appImage
        value: 'ajoyacharyya/bookinfo-productpage'
      - name: github-app-name
        value: bookinfo-productpage
      workspaces:
      - name: app-source
        emptyDir: {}
      - name: config-source
        emptyDir: {}
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-deploy-binding-bookinfo-productpage
  namespace: tekton-pipelines
spec:
  params:
  - name: buildRevision
    value: $(body.head_commit.id)
---
